[tools]
"cargo:https://github.com/LucioFranco/jj-spr" = "latest"
go = "latest"
jjui = "latest"
node = "latest"
ruby = "latest"
rust = "latest"
usage = "latest"
uv = "latest"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["ruby"]
